# Generated by Django 4.2.4 on 2023-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sign',
            field=models.BooleanField(default=False, verbose_name='Признак публикации продукта'),
        ),
    ]
