# Generated by Django 4.2.4 on 2023-10-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_product_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_description', 'изменение описания')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
