# Generated by Django 4.2.4 on 2023-10-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_description', 'изменение описания'), ('change_category', 'изменение категории')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': [('change_version_sign', 'изменение признака текущей версии')], 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
